version: '3'
services:
  redis:
    image: redis:latest
    volumes:
        - redis_data:/data
    ports:
        - '6379:6379'
    networks:
        - stan

  rabbitmq:
    image: rabbitmq:management
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
        - stan
      
  app:
    build:
        dockerfile: Dockerfile.dev
        context: ./node-app
    volumes:
        - /home/app/node-app/node_modules
        - ./node-app:/home/app/node-app/
    depends_on:
        - redis
        - rabbitmq
    networks:
        - stan

volumes:
  redis_data:

networks:
    stan:
